### ISSUE TITLE
FYI Google Maps API key changed

### ISSUE THREAD

**Issue by morphatic** [suzannahurst/astrology-bingo#1]
Hey there, super excited to see someone using the astrologyjs lib. Realized that I had left [my personal Google Maps API key](https://github.com/suzannahurst/astrology-bingo/blob/92846721c34e84f93ffb2fc129931925d29d6534/node_modules/astrologyjs/dist/astrologyjs-es6.js#L2361) in the code. I've regenerated the key, so the one that is in your repo won't work now. They're free, though, so [you can create your own key](https://developers.google.com/maps/documentation/javascript/get-api-key) and inject it into your code (though I recommend not following my example and figuring out how to keep it out of your public repo 😉). Cheers!

**Comment by snoozanna** [comment]
Hello Morgan
Thanks for your email - and for making the astrologyjs lib! I’m quite a
newbie so I'm not sure I've made the most of it yet but its been really fun
having a look around.
No problem - I've taken the key out.
Enjoy your week,
Suzanna
